[package]
name = "curvine-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
orpc = { workspace = true }
curvine-client-core = { workspace = true }
curvine-job-client = { workspace = true }
curvine-unified-fs = { workspace = true }
curvine-bench = { workspace = true }
curvine-ufs = { workspace = true }
curvine-config = { workspace = true }
curvine-error = { workspace = true }
curvine-fs-api = { workspace = true }
curvine-model = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
bytes = { workspace = true }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false}
comfy-table = { version = "7.2.2", default-features = false }
